sudo: required
services:
- docker

language: java
jdk:
- oraclejdk8


# found at https://github.com/GoogleCloudPlatform/Template/blob/master/.travis.yml
cache:
  directories:
      - $HOME/gcloud/

env:
      - PATH=$PATH:$HOME/gcloud/google-cloud-sdk/bin GOOGLE_APPLICATION_CREDENTIALS=$TRAVIS_BUILD_DIR/client_secrets.json #Other environment variables on same line

before_install:
        #ENCRYPT YOUR PRIVATE KEY (If you need authentication)
        # 1. Install and login to the Travis CLI:
        #       $ gem install travis
        #       $ travis login
        # 2. Move your json private key to client_secrets.json
        # 3. Run:
        #       $ travis encrypt-file client_secrets.json --add
        # 4. Commit changes:
        #       $ git add client_secrets.json.enc
        #       $ git commit client_secrets.json.enc .travis.yml

        - if [ ! -d $HOME/gcloud/google-cloud-sdk ]; then
                mkdir -p $HOME/gcloud &&
                wget https://dl.google.com/dl/cloudsdk/release/google-cloud-sdk.tar.gz --directory-prefix=$HOME/gcloud &&
                cd $HOME/gcloud &&
                tar xzf google-cloud-sdk.tar.gz &&
                printf '\ny\n\ny\ny\n' | ./google-cloud-sdk/install.sh &&
                cd $TRAVIS_BUILD_DIR;
          fi
          #        - gcloud -q components update

        - if [ -a client_secrets.json ]; then
                gcloud -q auth activate-service-account --key-file client_secrets.json;
          fi

install:
- docker version
- pip2.7 install --user setuptools==36.5.0
- pip2.7 install --user cwl-runner cwltool==1.0.20170828135420 schema-salad==2.6.20170806163416 avro==1.8.1 ruamel.yaml==0.14.12 requests==2.18.4
- wget https://github.com/broadinstitute/cromwell/releases/download/34/cromwell-34.jar
- ant deps

#script: 
#- cwltool checker_workflow_wrapping_workflow.cwl md5sum.json
#- cwltool checker_workflow_wrapping_tool.cwl md5sum.json
#- java -jar cromwell-34.jar run --inputs md5sum.wdl.json checker.wdl


