cwlVersion: v1.0
class: CommandLineTool
id: gatk4_applybqsr
requirements:
  - class: ShellCommandRequirement
  - class: InlineJavascriptRequirement
  - class: DockerRequirement
    dockerPull: us.gcr.io/broad-gotc-prod/genomes-in-the-cloud:2.3.2-1510681135
  - class: ResourceRequirement
    ramMin: 3500
baseCommand: [/usr/gitc/gatk4/gatk-launch, ApplyBQSR]
arguments:
  - position: 0
    shellQuote: false
    valueFrom: >-
      --javaOptions "-XX:+PrintFlagsFinal
      -XX:+PrintGCTimeStamps
      -XX:+PrintGCDateStamps
      -XX:+PrintGCDetails
      -Xloggc:gc_log.log
      -XX:GCTimeLimit=50
      -XX:GCHeapFreeLimit=10
      -Dsamjdk.compression_level=$(inputs.compression_level)
      -Xms3000m"
      --createOutputBamMD5
      --addOutputSAMProgramRecord
      -R $(inputs.ref_fasta.path)
      -I $(inputs.input_bam.path)
      --useOriginalQualities
      -O $(inputs.output_bam)
      -bqsr $(inputs.recalibration_report.path)
      -SQQ 10 -SQQ 20 -SQQ 30

inputs:
  - id: input_bam 
    type: File
    secondaryFiles: [^.bai]
  - id: output_bam
    type: string
  - id: recalibration_report
    type: File
  - id: sequence_group_interval
    type: 
      type: array
      items: string
      inputBinding:
        prefix: '-L'
        separate: true
  - id: ref_fasta
    type: File
    secondaryFiles: [.fai, ^.dict]
  - id: compression_level
    type: int

outputs:
  - id: recalibrated_bam 
    type: File
    outputBinding:
      glob: '*bam'
    secondaryFiles: 
      - ^.bai
      - ^.bam.md5
