cwlVersion: v1.0
class: CommandLineTool
id: gatk4_applybqsr
requirements:
  - class: ShellCommandRequirement
  - class: InlineJavascriptRequirement
  - class: DockerRequirement
    dockerPull: <docker>
  - class: ResourceRequirement
    ramMin: 3500
baseCommand: [gatk/gatk-launch, ApplyBQSR]
arguments:
  - position: 0
    shellQuote: false
    valueFrom: >-
      --javaOptions "-XX:+PrintFlagsFinal
      -XX:+PrintGCTimeStamps
      -XX:+PrintGCDateStamps
      -XX:+PrintGCDetails
      -Xloggc:gc_log.log
      -XX:GCTimeLimit=50
      -XX:GCHeapFreeLimit=10
      -Dsamjdk.compression_level=$(inputs.compression_level)
      -Xms3000m"
      --createOutputBamMD5
      --addOutputSAMProgramRecord
      -R $(inputs.ref_fasta)
      -I $(inputs.input_bam)
      --useOriginalQualities
      -O $(inputs.output_bam)
      -bqsr $(inputs.recalibration_report)
      -SQQ 10 -SQQ 20 -SQQ 30
      -L $(inputs.sequence_group_interval)

inputs:
  - input_bam: File
      secondaryFiles: [^.bai]
  - output_bam: string
  - recalibration_report: File
  - sequence_group_interval: array
      items: string
      inputBinding:
        prefix: '-L'
  - ref_dict: File
  - ref_fasta: File
  - ref_fasta_index: File
  - compression_level: int

outputs:
  - recalibrated_bam: File
      outbinding:
        glob: '*bam'
      secondaryFiles: [^.bai, .md5]


