cwlVersion: v1.0
class: CommandLineTool
id: converttocram
requirements:
  - class: ShellCommandRequirement
  - class: InlineJavascriptRequirement
  - class: DockerRequirement
    dockerPull: us.gcr.io/broad-gotc-prod/genomes-in-the-cloud:2.3.2-1510681135
  - class: ResourceRequirement
    ramMin: 3500
baseCommand: [samtools, view]
arguments:
  - position: 1
    shellQuote: false
    valueFrom: >-
      -C -T $(inputs.reference.path) -o $(inputs.input_bam.nameroot).cram $(inputs.input_bam.path)
      && samtools index $(inputs.input_bam.nameroot).cram
inputs:
  reference:
    type: File
    secondaryFiles: [.fai]
  input_bam:
    type: File
    secondaryFiles: [^.bai]
outputs:
  output:
    type: File
    outputBinding:
      glob: '*.cram'
    secondaryFiles: [.crai]
