cwlVersion: v1.0
class: ExpressionTool
id: expression_createsequencegrouping
requirements:
  - class: InlineJavascriptRequirement
inputs:
  sequence_grouping_with_unmapped_tsv:
    type:
      type: array
      items: File
      inputBinding:
        loadContents: true
        valueFrom: $(null)

outputs:
  sequence_grouping_array:
    type:
      type: array
      items:
        type: array
        items: string

expression: |
  ${
      var outer_array = [];
      for (var i=0; i< inputs.sequence_grouping_with_unmapped_tsv.length; i++) {
        var inner_array = [];
        var arrayofstring = inputs.sequence_grouping_with_unmapped_tsv[i].contents.split("\t");
        for (var j=0; j < arrayofstring.length; j++) {
          var sequence_contents = arrayofstring[j];
          inner_array.push(sequence_contents);
      }
        outer_array.push(inner_array);
     }
      return {"sequence_grouping_array": outer_array};
  }
