#!/usr/bin/env cwl-runner
cwlVersion: v1.0

# Get version of BWA
class: CommandLineTool
id: getBwaversion
requirements:
  - class: ShellCommandRequirement
  - class: DockerRequirement
    dockerPull: us.gcr.io/broad-gotc-prod/genomes-in-the-cloud:2.3.2-1510681135

inputs:
  []

stdout: version
outputs:
    version:
        type: stdout

baseCommand: ['/usr/gitc/bwa']
arguments:
  - valueFrom: "2>&1"
    position: 1
    shellQuote: False
  - valueFrom: "grep"
    position: 2
    prefix: "|"
  - valueFrom: "^Version"
    position: 3
    prefix: "-e"
  - valueFrom: "sed"
    position: 4
    prefix: "|"
  - valueFrom: "s/Version: //"
    position: 5

