#!/usr/bin/env cwl-runner

cwlVersion: v1.0

class: CommandLineTool

requirements:
  - class: ShellCommandRequirement
  - class: ResourceRequirement
    ramMin: 5000
  - class: DockerRequirement
    dockerPull: <docker>

# Sort BAM file by coordinate order and fix tag values for NM and UQ
baseCommand: [java, -Dsamjdk.compression_level=2, -jar, /picard.jar]
argument:
  - position: 0
    shellQuote: false
    valueFrom: >-
      SortSam
      INPUT=$(inputs.input_bam.path)
      OUTPUT=$(inputs.output_bam)
      SORT_ORDER="coordinate"
      CREATE_INDEX=true
      CREATE_MD5_FILE=true
      Max_RECOREDS_IN_RAM=300000

inputs:
  input_bam:
    type:File
  output_bam:
    type:string

outputs:
  output_sorted_bam
    type:File
    secondaryFiles:[^.bai, ^.bam.md5]
    outputBinding:
      glob:["*.bam", "*.bai",*.md5]
