#!/usr/bin/env cwl-runner

cwlVersion: v1.0

class: CommandLineTool

id: sortsam

requirements:
  - class: ShellCommandRequirement
  - class: ResourceRequirement
    ramMin: 5000
  - class: DockerRequirement
    dockerPull: us.gcr.io/broad-gotc-prod/genomes-in-the-cloud:2.3.2-1510681135

# Sort BAM file by coordinate order and fix tag values for NM and UQ
baseCommand: [java, -Dsamjdk.compression_level=2, -Xms4000m, -jar, /usr/gitc/picard.jar]
arguments:
  - position: 0
    shellQuote: false
    valueFrom: >-
      SortSam
      INPUT=$(inputs.input_bam.path)
      OUTPUT=$(inputs.output_bam)
      SORT_ORDER="coordinate"
      CREATE_INDEX=true
      CREATE_MD5_FILE=true
      MAX_RECORDS_IN_RAM=300000 

inputs:
  input_bam:
    type: File
  output_bam:
    type: string

outputs:
  output_sorted_bam:
    type: File
    outputBinding:
      glob: "*.bam"
    secondaryFiles:
      - ^.bai
      - .md5
